export const webProjects = [
  {
    id: "jr-express",
    name: "JR Express",
    category: "Logística urbana",
    url: "https://www.jrexpress.com.br/",
    domain: "jrexpress.com.br",
    image: "/images/portfolio/web/jr-express.jpg",
    imageHeight: 698,
    alt: "Site da JR Express com cena de entrega em 3D e chamada para solicitar transporte",
    description:
      "Uma entrega ganha vida em 3D. A cena acompanha o scroll e apresenta o serviço de forma visual, com um caminho direto para pedir transporte pelo WhatsApp.",
    features: ["Modelos 3D", "Animação no scroll", "Contato direto"],
  },
  {
    id: "hb-electronic-systems",
    name: "HB Electronic Systems",
    category: "Tecnologia para motos",
    url: "https://hbelectronicsystems.com.br/",
    domain: "hbelectronicsystems.com.br",
    image: "/images/portfolio/web/hb-electronic-systems.jpg",
    imageHeight: 692,
    alt: "Site da HB Electronic Systems com módulos de ignição e controle YPVS em destaque",
    description:
      "Tecnologia complexa, escolha mais simples. Uma vitrine de produtos com visual marcante, informações técnicas e navegação que ajuda o motociclista a encontrar o módulo para sua moto.",
    features: ["Vitrine de produtos", "Identidade visual", "Navegação por moto"],
  },
  {
    id: "audio-design",
    name: "Audio Design",
    category: "Áudio automotivo de alta fidelidade",
    url: "https://audiodesign.com.br/",
    domain: "audiodesign.com.br",
    image: "/images/portfolio/web/audio-design.jpg",
    imageHeight: 684,
    alt: "Site da Audio Design com Porsche em destaque e apresentação de projetos de som automotivo",
    description:
      "Uma abertura em vídeo acompanha o scroll e traduz o cuidado com cada detalhe. Projetos reais, marcas e serviços compõem uma experiência visual que valoriza o trabalho e convida a conversar sobre o próximo projeto.",
    features: ["Vídeo no scroll", "Projetos em destaque", "Direção visual"],
  },
  {
    id: "diff-reparos",
    name: "DIFF Reparos",
    category: "Eletrônica automotiva",
    url: "https://diffreparos.com.br/",
    domain: "diffreparos.com.br",
    image: "/images/portfolio/web/diff-reparos.jpg",
    imageHeight: 690,
    alt: "Site da DIFF Reparos com mecatrônica automotiva e chamada para avaliação técnica",
    description:
      "Precisão técnica também se comunica pelo visual. Vídeo de abertura e animações no scroll aproximam o visitante dos componentes, enquanto o conteúdo orienta oficinas e proprietários até a avaliação.",
    features: ["Abertura em vídeo", "Animação no scroll", "Conteúdo técnico"],
  },
  {
    id: "mecapro",
    name: "MecaPRO",
    category: "Software de gestão para oficinas",
    url: "https://mecapro.com.br/",
    domain: "mecapro.com.br",
    image: "/images/portfolio/web/mecapro.jpg",
    imageHeight: 678,
    alt: "Página do MecaPRO com demonstração de ordem de serviço e cotação de peças",
    description:
      "O visitante entende o produto vendo como ele funciona. Demonstrações de ordens de serviço, cotações e gestão do pátio tornam os recursos concretos e conduzem ao teste da plataforma.",
    features: ["Demonstração interativa", "Apresentação de software", "Jornada de conversão"],
  },
  {
    id: "creator-tools",
    name: "Creator Tools",
    category: "Plataforma de criação com IA",
    url: "https://creatortools.com.br/",
    domain: "creatortools.com.br",
    image: "/images/portfolio/web/creator-tools.jpg",
    imageHeight: 696,
    alt: "Página do Creator Tools com prévia de carrossel e recursos de criação com inteligência artificial",
    description:
      "Da ideia ao carrossel, o produto aparece em ação. Prévias visuais e uma apresentação clara dos recursos de IA ajudam o visitante a entender o processo e começar a criar.",
    features: ["Prévias do produto", "Inteligência artificial", "Jornada de criação"],
  },
] as const;
